// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
import '@testing-library/jest-dom'
import { expect, test, vi } from 'vitest'
import { render, getQueriesForElement } from '@lynx-js/react/testing-library'

import { App } from '../App.jsx'

test('App', async () => {
  const cb = vi.fn()

  render(
    <App
      onRender={() => {
        cb(`__MAIN_THREAD__: ${__MAIN_THREAD__}`)
      }}
    />,
  )
  expect(cb).toBeCalledTimes(1)
  expect(cb.mock.calls).toMatchInlineSnapshot(`
    [
      [
        "__MAIN_THREAD__: false",
      ],
    ]
  `)
  expect(elementTree.root).toMatchInlineSnapshot(`
    <page>
      <scroll-view
        class="app-container"
        scroll-y="true"
        style="height:100%"
      >
        <view
          class="card-container"
        >
          <view
            class="shop-section"
          >
            <view
              class="logo-wrapper"
            >
              <image
                class="shop-logo"
                mode="aspectFill"
                src="/src/assets/Rectangle%205.8.png"
              />
              <view
                class="badge-top-left-container"
              >
                <image
                  class="badge-top-left"
                  mode="aspectFit"
                  src="/src/assets/Group%202090053571.png"
                />
              </view>
            </view>
            <view
              class="info-column"
            >
              <text
                class="shop-name"
              >
                椒鸣椒麻馆(五道口店)
              </text>
              <view
                class="row-rating"
              >
                <view
                  class="stars-flex"
                >
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/0.png"
                  />
                </view>
                <text
                  class="text-score"
                >
                  3.5 可以一试
                </text>
                <text
                  class="text-reviews"
                >
                  170条评价
                </text>
              </view>
              <view
                class="row-meta"
              >
                <view
                  class="meta-left"
                >
                  <text
                    class="text-meta"
                  >
                    中餐
                  </text>
                  <text
                    class="text-meta margin-h"
                  >
                    龙柏地区
                  </text>
                  <text
                    class="text-meta"
                  >
                    人均¥220
                  </text>
                </view>
                <text
                  class="text-distance"
                >
                  842m
                </text>
              </view>
              <view
                class="row-tags"
              >
                <view
                  class="tag-pink"
                >
                  <image
                    class="icon-rank-bg"
                    mode="aspectFit"
                    src="/src/assets/Rectangle.png"
                  />
                  <text
                    class="text-pink-tag"
                  >
                    2025年上榜餐厅
                  </text>
                </view>
                <text
                  class="tag-gray"
                >
                  多人聚餐
                </text>
                <text
                  class="tag-gray"
                >
                  生日轰趴
                </text>
                <text
                  class="tag-gray"
                >
                  可订桌
                </text>
              </view>
            </view>
          </view>
          <wrapper>
            <view
              style="padding:20px"
            >
              <text>
                初次加载中...
              </text>
            </view>
          </wrapper>
        </view>
        <view
          class="card-container"
        >
          <view
            class="shop-section"
          >
            <view
              class="logo-wrapper"
            >
              <image
                class="shop-logo"
                mode="aspectFill"
                src="/src/assets/Rectangle%205.8.png"
              />
              <view
                class="badge-top-left-container"
              >
                <image
                  class="badge-top-left"
                  mode="aspectFit"
                  src="/src/assets/Group%202090053571.png"
                />
              </view>
            </view>
            <view
              class="info-column"
            >
              <text
                class="shop-name"
              >
                云海肴(中关村店)
              </text>
              <view
                class="row-rating"
              >
                <view
                  class="stars-flex"
                >
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/0.png"
                  />
                </view>
                <text
                  class="text-score"
                >
                  3.5 可以一试
                </text>
                <text
                  class="text-reviews"
                >
                  170条评价
                </text>
              </view>
              <view
                class="row-meta"
              >
                <view
                  class="meta-left"
                >
                  <text
                    class="text-meta"
                  >
                    中餐
                  </text>
                  <text
                    class="text-meta margin-h"
                  >
                    龙柏地区
                  </text>
                  <text
                    class="text-meta"
                  >
                    人均¥220
                  </text>
                </view>
                <text
                  class="text-distance"
                >
                  842m
                </text>
              </view>
              <view
                class="row-tags"
              >
                <view
                  class="tag-pink"
                >
                  <image
                    class="icon-rank-bg"
                    mode="aspectFit"
                    src="/src/assets/Rectangle.png"
                  />
                  <text
                    class="text-pink-tag"
                  >
                    2025年上榜餐厅
                  </text>
                </view>
                <text
                  class="tag-gray"
                >
                  多人聚餐
                </text>
                <text
                  class="tag-gray"
                >
                  生日轰趴
                </text>
                <text
                  class="tag-gray"
                >
                  可订桌
                </text>
              </view>
            </view>
          </view>
          <wrapper>
            <view
              style="padding:20px"
            >
              <text>
                初次加载中...
              </text>
            </view>
          </wrapper>
        </view>
        <view
          class="card-container"
        >
          <view
            class="shop-section"
          >
            <view
              class="logo-wrapper"
            >
              <image
                class="shop-logo"
                mode="aspectFill"
                src="/src/assets/Rectangle%205.8.png"
              />
              <view
                class="badge-top-left-container"
              >
                <image
                  class="badge-top-left"
                  mode="aspectFit"
                  src="/src/assets/Group%202090053571.png"
                />
              </view>
            </view>
            <view
              class="info-column"
            >
              <text
                class="shop-name"
              >
                西贝莜面村(朝阳大悦城店)
              </text>
              <view
                class="row-rating"
              >
                <view
                  class="stars-flex"
                >
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/0.png"
                  />
                </view>
                <text
                  class="text-score"
                >
                  3.5 可以一试
                </text>
                <text
                  class="text-reviews"
                >
                  170条评价
                </text>
              </view>
              <view
                class="row-meta"
              >
                <view
                  class="meta-left"
                >
                  <text
                    class="text-meta"
                  >
                    中餐
                  </text>
                  <text
                    class="text-meta margin-h"
                  >
                    龙柏地区
                  </text>
                  <text
                    class="text-meta"
                  >
                    人均¥220
                  </text>
                </view>
                <text
                  class="text-distance"
                >
                  842m
                </text>
              </view>
              <view
                class="row-tags"
              >
                <view
                  class="tag-pink"
                >
                  <image
                    class="icon-rank-bg"
                    mode="aspectFit"
                    src="/src/assets/Rectangle.png"
                  />
                  <text
                    class="text-pink-tag"
                  >
                    2025年上榜餐厅
                  </text>
                </view>
                <text
                  class="tag-gray"
                >
                  多人聚餐
                </text>
                <text
                  class="tag-gray"
                >
                  生日轰趴
                </text>
                <text
                  class="tag-gray"
                >
                  可订桌
                </text>
              </view>
            </view>
          </view>
          <wrapper>
            <view
              style="padding:20px"
            >
              <text>
                初次加载中...
              </text>
            </view>
          </wrapper>
        </view>
        <view
          class="card-container"
        >
          <view
            class="shop-section"
          >
            <view
              class="logo-wrapper"
            >
              <image
                class="shop-logo"
                mode="aspectFill"
                src="/src/assets/Rectangle%205.8.png"
              />
              <view
                class="badge-top-left-container"
              >
                <image
                  class="badge-top-left"
                  mode="aspectFit"
                  src="/src/assets/Group%202090053571.png"
                />
              </view>
            </view>
            <view
              class="info-column"
            >
              <text
                class="shop-name"
              >
                海底捞(三里屯店)
              </text>
              <view
                class="row-rating"
              >
                <view
                  class="stars-flex"
                >
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84_%E5%89%AF%E6%9C%AC.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/%E7%BC%96%E7%BB%84.png"
                  />
                  <image
                    class="icon-star"
                    mode="aspectFit"
                    src="/src/assets/0.png"
                  />
                </view>
                <text
                  class="text-score"
                >
                  3.5 可以一试
                </text>
                <text
                  class="text-reviews"
                >
                  170条评价
                </text>
              </view>
              <view
                class="row-meta"
              >
                <view
                  class="meta-left"
                >
                  <text
                    class="text-meta"
                  >
                    中餐
                  </text>
                  <text
                    class="text-meta margin-h"
                  >
                    龙柏地区
                  </text>
                  <text
                    class="text-meta"
                  >
                    人均¥220
                  </text>
                </view>
                <text
                  class="text-distance"
                >
                  842m
                </text>
              </view>
              <view
                class="row-tags"
              >
                <view
                  class="tag-pink"
                >
                  <image
                    class="icon-rank-bg"
                    mode="aspectFit"
                    src="/src/assets/Rectangle.png"
                  />
                  <text
                    class="text-pink-tag"
                  >
                    2025年上榜餐厅
                  </text>
                </view>
                <text
                  class="tag-gray"
                >
                  多人聚餐
                </text>
                <text
                  class="tag-gray"
                >
                  生日轰趴
                </text>
                <text
                  class="tag-gray"
                >
                  可订桌
                </text>
              </view>
            </view>
          </view>
          <wrapper>
            <view
              style="padding:20px"
            >
              <text>
                初次加载中...
              </text>
            </view>
          </wrapper>
        </view>
      </scroll-view>
    </page>
  `)
  const {
    findByText,
  } = getQueriesForElement(elementTree.root!)
  const element = await findByText('Tap the logo and have fun!')
  expect(element).toBeInTheDocument()
  expect(element).toMatchInlineSnapshot(`
    <text
      class="Description"
    >
      Tap the logo and have fun!
    </text>
  `)
})
